# Generated by Django 5.0.4 on 2024-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procData", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="dbQueriedUsers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
    ]
