# Generated by Django 4.2.12 on 2024-05-07 13:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("procData", "0002_dbqueriedusers"),
    ]

    operations = [
        migrations.AddField(
            model_name="dbqueriedusers",
            name="added",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dbqueriedusers",
            name="github_account",
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
