# Generated by Django 4.2.12 on 2024-05-07 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("procData", "0003_dbqueriedusers_added_dbqueriedusers_github_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dbqueriedusers",
            name="github_account",
            field=models.CharField(max_length=100),
        ),
    ]
